/*
 * generated by Xtext 2.27.0.M2
 */
package gendev.bot.turtle.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TurtleLangUiModule extends AbstractTurtleLangUiModule {

	public TurtleLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
