/*
 * generated by Xtext 2.27.0.M2
 */
package gendev.bot.turtle.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class TurtleLangOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
