/*
 * generated by Xtext 2.27.0.M2
 */
package gendev.bot.turtle.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import gendev.bot.turtle.TurtleLangRuntimeModule;
import gendev.bot.turtle.TurtleLangStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TurtleLangIdeSetup extends TurtleLangStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TurtleLangRuntimeModule(), new TurtleLangIdeModule()));
	}
	
}
