/*
 * generated by Xtext 2.27.0.M2
 */
package gendev.bot.turtle;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TurtleLangStandaloneSetup extends TurtleLangStandaloneSetupGenerated {

	public static void doSetup() {
		new TurtleLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
