/*
 * generated by Xtext 2.27.0.M2
 */
package gendev.bot.turtle;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TurtleLangRuntimeModule extends AbstractTurtleLangRuntimeModule {
}
